### PR TITLE
Bump Bio-Formats version to 5.3.3

### PR DESCRIPTION
**Pull request by sbesson**
This should update the Hub image to use Bio-Formats 5.3.3

### CODE REVIEW

**Comment by joshmoore** [comment]
Proposed tag for this image once green? `5.3.3` as discussed?

**Comment by sbesson** [comment]
I would think 5.3.3 would be appropriate for these images distributing a component in a given environment as discussed. Main question here is do we want to add additional components to the repo before a first tag (Readme - is there a template? or minimal m file)?

**Comment by joshmoore** [comment]
Probably the best template is as if creating an official repo: https://docs.docker.com/docker-hub/official_repos/ (Previously, for example, there was a way to set the short description. I'm not seeing that at the moment)

**Comment by sbesson** [comment]
@joshmoore pushed a minimal Readme to update the long description on DockerHub. It looks like the short description update is a feature specific to the official images.

**Comment by joshmoore** [comment]
Cool. Merging. Once the build on hub is green, it'll be time to tag & push.

**Pull request merged**
